.TH shortest_path_distribution 1 "June 20, 2011" "version 1.0" "LPmade User Commands"
.SH NAME
shortest_path_distribution \- output the shortest paths between all pairs of vertices
.SH SYNOPSIS
.B shortest_path_distribution
[OPTIONS] ...
.SH DESCRIPTION
Produces the distribution of |V| choose 2 shortest path lengths in the network excluding those with non-reachability. The output places each path length on its own line ordered first by source and then by target.
.SH OPTIONS
.TP
.B \-h
display usage information
.SH RETURN VALUE
Returns 0 on successful execution (not necessarily successful completion) or 1 if argument specification is incorrect or the requested predictor is not included in predict.
.SH EXAMPLE
.PP
< mynet.net shortest_path_distribution > sp_dist.txt
.PP
Input:
.RS
*Vertices 9
0 0
1 2
2 3
3 4
4 5
5 7
6 18
7 47
8 285
*Edges 8
0 1 1
0 4 2
0 5 1
2 6 1
5 3 1
6 2 1
7 1 1
8 7 1
.RE
.PP
Output:
.RS
1
2
1
1
1
1
1
1
2
1
.RE
.SH COPYRIGHT
.PP
Copyright (C) 2011 Ryan N. Lichtenwalter
.PP
LPmade is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. LPmade is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with LPmade. If not, see <http://www.gnu.org/licenses/>.

